apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "chart.labels" . | indent 4 }}
    app.kubernetes.io/name: "api"
    app.kubernetes.io/component: "api"
type: Opaque
data:
  SECRET_KEY: {{ .Values.secret_key | toString | b64enc }}

  POSTGRES_USER: {{ .Values.postgresql.postgresqlUsername | toString | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.postgresqlPassword | toString | b64enc }}
  POSTGRES_DB: {{ .Values.postgresql.postgresqlDatabase | toString | b64enc }}