apiVersion:  v1
kind:  ConfigMap
metadata: 
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "chart.labels" . | indent 4 }}
    app.kubernetes.io/name: "api"
    app.kubernetes.io/component: "api"
data:
  DJANGO_SETTINGS_MODULE: "pantheon.settings.base"
  SITE_URL: "https://api.pantheon.joshpaulchan.com"
  DEBUG: {{ .Values.app.debug | quote }}

  HOST: 0.0.0.0
  PORT: {{ .Values.service.port | quote }}

  # if managed-in-cluster, point us to that postgres subchart service, otherwise, point us to localhost
  POSTGRES_HOST: {{if .Values.postgresql.managedByApp }}{{ .Release.Name }}-postgresql{{else}}localhost{{end}}
  POSTGRES_PORT: {{ .Values.postgresql.service.port | quote }}

  {{- if .Values.redis.enabled }}
  REDIS_HOST: {{ .Release.Name }}-redis
  REDIS_PORT: {{ .Values.redis.service.port | quote }}
  {{- end }}