apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "chart.labels" . | indent 4 }}
    app.kubernetes.io/name: api
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
{{- include "chart.labels" . | indent 4 }}
    app.kubernetes.io/name: api
    app.kubernetes.io/component: api
status:
  loadBalancer: {}