apiVersion:  v1
kind: ConfigMap
metadata: 
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app-infra-starter.labels" . | nindent 4 }}
data:
  # if managed-in-cluster, point us to that postgres subchart service, otherwise, point us to localhost
  POSTGRES_HOST: {{if .Values.postgresql.managedByApp }}{{ .Release.Name }}-postgresql{{else}}localhost{{end}}
  POSTGRES_PORT: {{ .Values.postgresql.service.port | quote }}
  {{- if or .Values.redis.enabled .Values.redis.parentComponent }}
  # if a sub component, then trim our component off the release name (if that exists) then replace it with parent component
  REDIS_HOST: {{ if .Values.redis.parentComponent }}{{ .Release.Name | trimSuffix .Values.component | cat .Values.redis.parentComponent "-redis-master"  }}{{else}}{{ .Release.Name }}-redis-master{{end}}
  REDIS_PORT: {{ .Values.redis.service.port | quote }}
  {{- end }}
  {{/* would be nice to use toYaml, but that's a PITA somehow? */}}
  {{- range $key, $value := .Values.app.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  