apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.component }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app-infra-starter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "app-infra-starter.selectorLabels" . | nindent 6 }}
  strategy: {}
  template:
    metadata:
      labels:
        {{- include "app-infra-starter.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "app-infra-starter.serviceAccountName" . }}
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Values.component }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-{{ .Values.component }}
            - secretRef:
                name: {{ .Release.Name }}-{{ .Values.component }}
          {{- if .Values.image.command }}
          command:
            {{- range .Values.image.command }}
            - {{ . }}
            {{- end }}
          {{ end }}
          {{- if .Values.image.args }}
          args:
            {{- range .Values.image.args }}
            - {{ . }}
            {{- end }}
          {{ end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /healthcheck/
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          {{- end }}
        {{- $relname := print .Release.Name "-postgresql" -}}
        {{- with .Values.postgresql }}
        {{- if and (not .managedByApp) .gcpProxy.enabled }}
        - name: {{ $relname }}
          image: {{ .gcpProxy.image.repository }}:{{ .gcpProxy.image.tag }}
          {{- if .gcpProxy.image.command }}
          command:
            {{- range .gcpProxy.image.command }}
            - {{ . }}
            {{- end }}
          {{- end }}
        {{end}}
        {{end}}
status: {}