{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app-infra-starter.labels" . | nindent 4 }} 
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
     {{ $key }}: {{ $value }}
  {{- end }}
spec:
  ingressClassName: "nginx-dos"
  {{- if .Values.ingress.tlsEnabled }}
  tls:
  - hosts:
    - {{ print .Values.ingress.subDomain .Release.Name "." .Values.ingress.topLevelDomain }}
    secretName: {{ .Release.Name }}-cert
  {{ end }}
  rules:
  - host: {{ print .Values.ingress.subDomain .Release.Name "." .Values.ingress.topLevelDomain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              name: http
{{- end }}