apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app-infra-starter.labels" . | nindent 4 }} 
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgresql.postgresqlUsername | toString | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.postgresqlPassword | toString | b64enc }}
  POSTGRES_DB: {{ .Values.postgresql.postgresqlDatabase | toString | b64enc }}
  {{- if .Values.redis.auth.enabled }}
  REDIS_PASSWORD: {{ .Values.redis.auth.password | toString | b64enc }}
  {{- end }}
{{- range $key, $value := .Values.app.secrets }}
  {{ $key }}: {{ $value | toString | b64enc }}
{{- end }}