apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.component }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app-infra-starter.labels" . | nindent 4 }} 
type: Opaque
data:
  POSTGRES_USER: {{ .Values.app.secrets.postgresql.postgresqlUsername | toString | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.app.secrets.postgresql.postgresqlPassword | toString | b64enc }}
  POSTGRES_DB: {{ .Values.app.secrets.postgresql.postgresqlDatabase | toString | b64enc }}

{{- range $key, $value := .Values.app.secrets }}
  {{ $key }}: {{ $value | toString | b64enc }}
{{- end }}