apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.component }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "app-infra-starter.labels" . | indent 4 }} 
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgresql.postgresqlUsername | toString | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.postgresqlPassword | toString | b64enc }}
  POSTGRES_DB: {{ .Values.postgresql.postgresqlDatabase | toString | b64enc }}

  {{- range $key, $value := .Values.app.secret }}
    {{ $key }}: {{ $value | toString | b64enc }}
  {{- end }}