{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm.serviceAccountName" . }}
  labels:
{{- include "app-infra-starter.labels" . | indent 4 }}
    "meta.helm.sh/release-name": {{ .Release.Namespace }}
  annotations:
  {{- range $key, $value := .Values.serviceAccount.annotations }}
     {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end}}