apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.component }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "app-infra-starter.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
{{- include "app-infra-starter.selectorLabels" . | indent 4 }} 
status:
  loadBalancer: {}