{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app-infra-starter.serviceAccountName" . }}
  labels:
    {{- include "app-infra-starter.labels" . | nindent 4 }}
  annotations:
  {{- range $key, $value := .Values.serviceAccount.annotations }}
     {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end}}