apiVersion: v2
name: app-infra-starter
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.2.0

# Seems like some pain with subcharts and making sure the lockfile stays in-sync? https://github.com/helm/helm/issues/8955
dependencies:
  - name: postgresql
    version: 10.9.1
    condition: postgresql.managedByApp
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: 15.7.5
    condition: redis.enabled
    repository: https://charts.bitnami.com/bitnami
